# Generated by Django 2.1.5 on 2019-05-07 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='groups',
            table='class',
        ),
    ]
