# Generated by Django 2.1.5 on 2019-04-24 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='number',
        ),
    ]
