# Generated by Django 2.1.5 on 2019-04-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manage', '0002_remove_groups_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
