# Generated by Django 2.1.5 on 2019-04-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manage', '0003_students_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stutest',
            name='number',
        ),
        migrations.AddField(
            model_name='tests',
            name='deadline',
            field=models.CharField(default='无', max_length=100),
        ),
        migrations.AlterField(
            model_name='tests',
            name='number',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
