# Generated by Django 2.1.5 on 2019-04-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manage', '0004_auto_20190425_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='details',
            field=models.TextField(default=''),
        ),
    ]
