# Generated by Django 2.1.5 on 2019-04-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manage', '0005_tests_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests',
            name='number',
        ),
        migrations.AddField(
            model_name='tests',
            name='group_id',
            field=models.IntegerField(default=0),
        ),
    ]
