# Generated by Django 2.1.5 on 2019-05-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manage', '0008_tests_result_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='stutest',
            name='group',
            field=models.CharField(default='B160905', max_length=50),
        ),
    ]
