# Generated by Django 2.1.5 on 2019-05-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manage', '0009_stutest_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='permission',
            field=models.IntegerField(default=4),
        ),
    ]
