# Generated by Django 2.1.5 on 2019-05-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manage', '0010_auto_20190505_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stutest',
            name='path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
